export const AUTH_USER_NATIVE = 'AUTH_USER_NATIVE';

export const FILES_UPLOADING = 'FILES_UPLOADING';
export const UPLOAD_LOADERS_DISPLAYED = 'UPLOADING_LOADERS_DISPLAYED';
export const FILES_UPLOADED = 'FILES_UPLOADED';
export const FILES_COLLECTED = 'FILES_COLLECTED';

export const POST_CREATING = 'POST_CREATING';
export const POST_LOADER_DISPLAYED = 'POST_LOADER_DISPLAYED';
export const POST_CREATED = 'POST_CREATED';

export const GET_ERRORS = 'GET_ERRORS';
export const NETWORK_ERROR = 'NETWORK_ERROR';
export const AUTH_ERROR = 'AUTH_ERROR';
export const POST_ERROR = 'POST_ERROR';
export const UPLOAD_ERROR = 'UPLOAD_ERROR';
export const RESET_ERRORS = 'RESET_ERRORS';
