export const AUTH_SET_USER = 'AUTH_SET_USER';
export const AUTH_UNSET_USER = 'AUTH_UNSET_USER';

export const FOLLOW_RESET = 'FOLLOW_RESET';
export const FOLLOWERS_FETCHING = 'FOLLOWERS_FETCHING';
export const FOLLOWERS_FETCHED = 'FOLLOWERS_FETCHED';
export const FOLLOWING_FETCHING = 'FOLLOWING_FETCHING';
export const FOLLOWING_FETCHED = 'FOLLOWING_FETCHED';
export const FOLLOW_SETMODE = 'FOLLOW_SETMODE';

export const FILES_UPLOADED = 'FILES_UPLOADED';
export const FILES_UPLOADING = 'FILES_UPLOADING';
export const FILES_COLLECTED = 'FILES_COLLECTED';

export const PERSON_RESET = 'PERSON_RESET';
export const PERSON_FETCHING = 'PERSON_FETCHING';
export const PERSON_FETCHED = 'PERSON_FETCHED';
export const PERSON_FOLLOWING = 'PERSON_FOLLOWING';
export const PERSON_FOLLOWED = 'PERSON_FOLLOWED';
export const PERSON_UNFOLLOWING = 'PERSON_UNFOLLOWING';
export const PERSON_UNFOLLOWED = 'PERSON_UNFOLLOWED';

export const SEARCH_RESET = 'SEARCH_RESET';
export const SEARCHING = 'SEARCHING';
export const SEARCHED = 'SEARCHED';

export const POSTS_RESET = 'POSTS_RESET';
export const POSTS_FETCHING = 'POSTS_FETCHING';
export const POSTS_FETCHED = 'POSTS_FETCHED';
export const POST_CREATING = 'POST_CREATING';
export const POST_CREATED = 'POST_CREATED';
export const POST_SELECTED = 'POST_SELECTED';
export const POST_UNSELECTED = 'POST_UNSELECTED';
export const POST_REACTION_SET = 'POST_REACTION_SET';
export const POST_DETAILS_FETCHING = 'POST_DETAILS_FETCHING';
export const POST_VIEWS_RESET = 'POST_VIEWS_RESET';
export const POST_VIEWS_FETCHED = 'POST_VIEWS_FETCHED';
export const POST_REACTIONS_RESET = 'POST_REACTIONS_RESET';
export const POST_REACTIONS_FETCHED = 'POST_REACTIONS_FETCHED';
export const POST_COMMENTS_RESET = 'POST_COMMENTS_RESET';
export const POST_COMMENTS_FETCHED = 'POST_COMMENTS_FETCHED';

export const AUTH_ERROR = 'AUTH_ERROR';
export const PERSON_ERROR = 'PERSON_ERROR';
export const SEARCH_ERROR = 'SEARCH_ERROR';
export const POST_ERROR = 'POST_ERROR';
export const UPLOAD_ERROR = 'UPLOAD_ERROR';
export const NETWORK_ERROR = 'NETWORK_ERROR';
export const RESET_ERRORS = 'RESET_ERRORS';
export const GET_ERRORS = 'GET_ERRORS';
export const FOLLOW_ERROR = 'FOLLOW_ERROR';